/**
 * S1 POSTBACK RECEIVER → BigQuery
 *
 * Netlify serverless function that receives postback events from System1
 * and writes them directly to BigQuery for the CAPI pipeline to pick up.
 *
 * Handles both:
 *   - click_track_url  (immediate, no revenue)
 *   - rev_click_track_url (S1 sends these in batches ~1h after the click,
 *     with estimated revenue)
 *
 * Every postback gets our own event_id (random UUID) the moment it arrives.
 * s1-capi-sender uses it as the Meta event_id, one Purchase per postback.
 * We deliberately do not key on anything S1 sends beyond click_id/type/
 * revenue: S1 splits a session's revenue evenly across its ad clicks, so
 * distinct postbacks routinely share click, second and value.
 *
 * S1 sends a GET request to this endpoint. The click_id param links
 * back to the uid generated by the redirect function.
 *
 * DURABILITY (write-ahead, see _shared/durable-bq.mts):
 *   1. The row is written to the Netlify Blobs "bq-pending" store BEFORE we
 *      answer S1. That small single-key write replaces the old per-day
 *      .jsonl backup, which re-downloaded and re-uploaded the whole day's
 *      file on every postback (slower as the day grew, and concurrent
 *      postbacks could overwrite each other's lines).
 *   2. After answering, the BigQuery insert runs with a cached token and
 *      retries. On success the pending entry is deleted.
 *   3. Anything still pending (insert failed, or the function died) is
 *      re-inserted by s1-bq-pending-replay every 10 minutes with the same
 *      insertId. A duplicate row is harmless: s1-capi-sender dedupes on
 *      event_id.
 *   If the pending write itself fails we still answer 200 and fall back to
 *   insert-with-retry, then park-on-failure.
 *
 * ENV VARS REQUIRED (set in Netlify UI):
 *   GCP_SERVICE_ACCOUNT_KEY - Full JSON service account key
 *
 * Deploy: Place in netlify/functions/s1-postback.mts on redirector-edge
 */

import type { Context, Config } from "@netlify/functions";
import {
  SCOPE_BQ_INSERT, deletePending, insertOrPark, insertWithRetry,
  parseSaKey, pendingKey, putPending,
} from "./_shared/durable-bq.mts";

// ── BigQuery config ──
const BQ_DATASET = "my_dataset";
const BQ_TABLE = "s1_postbacks";

// ── Main handler ──

export default async (req: Request, context: Context) => {
  try {
    const url = new URL(req.url);

    // S1 fires a GET request to this URL
    const click_id = url.searchParams.get("click_id");
    const type = url.searchParams.get("type") || "unknown";
    const revenue = url.searchParams.get("revenue");

    // Always return 200 to S1 — don't let errors cause retries
    if (!click_id) {
      console.warn("s1-postback: missing click_id", {
        params: Object.fromEntries(url.searchParams.entries()),
      });
      return new Response("OK", { status: 200 });
    }

    const now = Math.floor(Date.now() / 1000);
    const receivedAt = new Date().toISOString();

    const revenueValue =
      revenue && revenue !== "ESTIMATED_CONVERSION_VALUE"
        ? parseFloat(revenue)
        : null;

    const event = {
      event_id: crypto.randomUUID(),
      click_id,
      type,
      revenue: revenueValue,
      received_at: now,
      received_at_iso: receivedAt,
      source: "s1_postback",
      raw_params: JSON.stringify(
        Object.fromEntries(url.searchParams.entries())
      ),
    };

    console.log("s1-postback received:", { click_id, type, revenue: revenueValue });

    // ── 1. Write-ahead: park the row in the pending store before answering ──
    const bqRow = { insertId: event.event_id, json: event };
    const walKey = pendingKey(BQ_DATASET, BQ_TABLE, event.event_id);
    let walOk = false;
    try {
      await putPending(walKey, {
        dataset: BQ_DATASET, table: BQ_TABLE, rows: [bqRow],
        first_failed_at: receivedAt, attempts: 0,
        last_error: "write-ahead (insert not confirmed yet)", source: "s1-postback",
      });
      walOk = true;
    } catch (err: any) {
      console.error("s1-postback: write-ahead failed, continuing with direct insert:", err?.message);
    }

    // ── 2. Insert into BigQuery after answering S1 ──
    context.waitUntil(
      (async () => {
        if (walOk) {
          try {
            await insertWithRetry(parseSaKey(Netlify.env.get("GCP_SERVICE_ACCOUNT_KEY")),
              SCOPE_BQ_INSERT, BQ_DATASET, BQ_TABLE, [bqRow]);
            await deletePending(walKey).catch((e: any) =>
              // Row is in BigQuery; replay may insert it again, which is harmless.
              console.warn("s1-postback: inserted but could not clear write-ahead entry:", e?.message));
            console.log("s1-postback: BigQuery insert OK", { click_id, type });
          } catch (err: any) {
            // Entry stays in the pending store; the replay job retries it.
            console.warn("s1-postback: insert failed, left for replay:", err?.message);
          }
        } else {
          const r = await insertOrPark({
            saKeyRaw: Netlify.env.get("GCP_SERVICE_ACCOUNT_KEY"), scope: SCOPE_BQ_INSERT,
            dataset: BQ_DATASET, table: BQ_TABLE, rows: [bqRow], source: "s1-postback",
          });
          console.log(`s1-postback: ${r}`, { click_id, type });
        }
      })()
    );

    return new Response("OK", { status: 200 });
  } catch (e: any) {
    console.error("s1-postback error:", e?.message || e);
    return new Response("OK", { status: 200 });
  }
};

export const config: Config = {
  path: "/api/s1-postback",
};
