/**
 * S1 POSTBACK RECEIVER
 *
 * Netlify serverless function that receives postback events from System1.
 * Handles both:
 *   - click_track_url  (immediate, no revenue)
 *   - rev_click_track_url (6hr delay, includes estimated revenue)
 *
 * S1 sends a GET request to this endpoint. The click_id param links
 * back to the uid generated by the redirect function.
 *
 * Deduplication strategy:
 *   Both events are stored with a "type" field ("click" vs "revenue").
 *   The revenue event is the source of truth for revenue attribution.
 *   Use the BigQuery dedup view (see s1_postbacks_deduped) to get
 *   one row per conversion with revenue filled in.
 *
 * Deploy: Place in netlify/functions/s1-postback.mts on redirector-edge
 */

import type { Context, Config } from "@netlify/functions";
import { getStore } from "@netlify/blobs";

const COLLECTOR_URL =
  "https://click-collector-583868590168.us-central1.run.app/collect";

export default async (req: Request, context: Context) => {
  try {
    const url = new URL(req.url);

    // S1 fires a GET request to this URL
    const click_id = url.searchParams.get("click_id");
    const type = url.searchParams.get("type") || "unknown";
    const revenue = url.searchParams.get("revenue");

    // Always return 200 to S1 — don't let errors cause retries
    if (!click_id) {
      console.warn("s1-postback: missing click_id", {
        params: Object.fromEntries(url.searchParams.entries()),
      });
      return new Response("OK", { status: 200 });
    }

    const now = Math.floor(Date.now() / 1000);
    const receivedAt = new Date().toISOString();

    const event = {
      click_id,
      type, // "click" or "revenue"
      revenue: revenue && revenue !== "ESTIMATED_CONVERSION_VALUE"
        ? parseFloat(revenue)
        : null,
      received_at: now,
      received_at_iso: receivedAt,
      raw_params: Object.fromEntries(url.searchParams.entries()),
      source: "s1_postback",
    };

    console.log("s1-postback received:", { click_id, type, revenue });

    // ── 1. Store in Netlify Blobs (reliable, immediate) ──
    const store = getStore({ name: "s1-postbacks", consistency: "strong" });
    const day = receivedAt.slice(0, 10);
    const key = `postbacks/${day}.jsonl`;
    const existing = await store.get(key, { type: "text" });
    const line = JSON.stringify(event) + "\n";
    await store.set(key, (existing || "") + line);

    // ── 2. Forward to Cloud Run collector for BigQuery ingestion ──
    // The collector should route events with source:"s1_postback"
    // to the s1_postbacks table. If it doesn't yet, the Blobs
    // backup ensures no data is lost.
    const controller = new AbortController();
    const kill = setTimeout(() => controller.abort(), 3000);

    context.waitUntil(
      fetch(COLLECTOR_URL, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(event),
        signal: controller.signal,
      })
        .then((res) => {
          console.log("s1-postback collector response:", res.status);
        })
        .catch((err) => {
          console.warn("s1-postback collector error:", err?.message);
        })
        .finally(() => clearTimeout(kill))
    );

    return new Response("OK", { status: 200 });
  } catch (e: any) {
    console.error("s1-postback error:", e?.message || e);
    // Always 200 — S1 doesn't need to know about our errors
    return new Response("OK", { status: 200 });
  }
};

export const config: Config = {
  path: "/api/s1-postback",
};
