/**
 * S1 POSTBACK RECEIVER → BigQuery
 *
 * Netlify serverless function that receives postback events from System1
 * and writes them directly to BigQuery for the CAPI pipeline to pick up.
 *
 * Handles both:
 *   - click_track_url  (immediate, no revenue)
 *   - rev_click_track_url (6hr delay, includes estimated revenue)
 *
 * S1 sends a GET request to this endpoint. The click_id param links
 * back to the uid generated by the redirect function.
 *
 * ENV VARS REQUIRED (set in Netlify UI):
 *   GCP_SERVICE_ACCOUNT_KEY - Full JSON service account key
 *
 * Deploy: Place in netlify/functions/s1-postback.mts on redirector-edge
 */

import type { Context, Config } from "@netlify/functions";
import { getStore } from "@netlify/blobs";

// ── BigQuery config ──
const BQ_PROJECT = "carbon-storm-422904-n0";
const BQ_DATASET = "my_dataset";
const BQ_TABLE = "s1_postbacks";

// ── JWT / Google Auth helpers (no npm packages needed) ──

function base64url(input: string | ArrayBuffer): string {
  const bytes =
    typeof input === "string"
      ? new TextEncoder().encode(input)
      : new Uint8Array(input);
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

async function signJwt(
  payload: Record<string, unknown>,
  privateKeyPem: string
): Promise<string> {
  const header = { alg: "RS256", typ: "JWT" };
  const segments = [
    base64url(JSON.stringify(header)),
    base64url(JSON.stringify(payload)),
  ];
  const signingInput = segments.join(".");

  // Import the PEM key
  const pemBody = privateKeyPem
    .replace(/-----BEGIN PRIVATE KEY-----/, "")
    .replace(/-----END PRIVATE KEY-----/, "")
    .replace(/\s/g, "");
  const keyBuffer = Uint8Array.from(atob(pemBody), (c) => c.charCodeAt(0));

  const cryptoKey = await crypto.subtle.importKey(
    "pkcs8",
    keyBuffer,
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );

  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    cryptoKey,
    new TextEncoder().encode(signingInput)
  );

  return signingInput + "." + base64url(signature);
}

async function getAccessToken(serviceAccountKey: {
  client_email: string;
  private_key: string;
}): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const jwt = await signJwt(
    {
      iss: serviceAccountKey.client_email,
      scope: "https://www.googleapis.com/auth/bigquery.insertdata",
      aud: "https://oauth2.googleapis.com/token",
      iat: now,
      exp: now + 3600,
    },
    serviceAccountKey.private_key
  );

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: `grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${jwt}`,
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Google OAuth failed (${res.status}): ${text}`);
  }

  const data = (await res.json()) as { access_token: string };
  return data.access_token;
}

async function insertIntoBigQuery(
  accessToken: string,
  row: Record<string, unknown>
): Promise<void> {
  const url = `https://bigquery.googleapis.com/bigquery/v2/projects/${BQ_PROJECT}/datasets/${BQ_DATASET}/tables/${BQ_TABLE}/insertAll`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      rows: [{ json: row }],
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`BigQuery insert failed (${res.status}): ${text}`);
  }

  const result = (await res.json()) as {
    insertErrors?: Array<{ errors: Array<{ message: string }> }>;
  };
  if (result.insertErrors?.length) {
    throw new Error(
      `BigQuery insert errors: ${JSON.stringify(result.insertErrors)}`
    );
  }
}

// ── Main handler ──

export default async (req: Request, context: Context) => {
  try {
    const url = new URL(req.url);

    // S1 fires a GET request to this URL
    const click_id = url.searchParams.get("click_id");
    const type = url.searchParams.get("type") || "unknown";
    const revenue = url.searchParams.get("revenue");

    // Always return 200 to S1 — don't let errors cause retries
    if (!click_id) {
      console.warn("s1-postback: missing click_id", {
        params: Object.fromEntries(url.searchParams.entries()),
      });
      return new Response("OK", { status: 200 });
    }

    const now = Math.floor(Date.now() / 1000);
    const receivedAt = new Date().toISOString();

    const revenueValue =
      revenue && revenue !== "ESTIMATED_CONVERSION_VALUE"
        ? parseFloat(revenue)
        : null;

    const event = {
      click_id,
      type,
      revenue: revenueValue,
      received_at: now,
      received_at_iso: receivedAt,
      source: "s1_postback",
      raw_params: JSON.stringify(
        Object.fromEntries(url.searchParams.entries())
      ),
    };

    console.log("s1-postback received:", { click_id, type, revenue: revenueValue });

    // ── 1. Store in Netlify Blobs (backup) ──
    const store = getStore({ name: "s1-postbacks", consistency: "strong" });
    const day = receivedAt.slice(0, 10);
    const key = `postbacks/${day}.jsonl`;
    const existing = await store.get(key, { type: "text" });
    const line = JSON.stringify(event) + "\n";
    await store.set(key, (existing || "") + line);

    // ── 2. Write directly to BigQuery ──
    const saKeyRaw = Netlify.env.get("GCP_SERVICE_ACCOUNT_KEY");
    if (saKeyRaw) {
      context.waitUntil(
        (async () => {
          try {
            const saKey = JSON.parse(saKeyRaw);
            const token = await getAccessToken(saKey);
            await insertIntoBigQuery(token, event);
            console.log("s1-postback: BigQuery insert OK", { click_id, type });
          } catch (err: any) {
            console.error("s1-postback: BigQuery insert failed:", err?.message);
          }
        })()
      );
    } else {
      console.warn("s1-postback: GCP_SERVICE_ACCOUNT_KEY not set, skipping BigQuery");
    }

    return new Response("OK", { status: 200 });
  } catch (e: any) {
    console.error("s1-postback error:", e?.message || e);
    return new Response("OK", { status: 200 });
  }
};

export const config: Config = {
  path: "/api/s1-postback",
};
