[[edge_functions]]
path = "/*"
function = "redirect"

[build]
  functions = "netlify/functions"   # <— make Functions directory explicit

[functions]
  directory = "netlify/functions"   # <— same here (being explicit helps)
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
