[[edge_functions]]
path = "/*"
function = "redirect"

[build]
  functions = "netlify/functions"   # <— make Functions directory explicit
  command = "cd netlify/functions && npm install"

[functions]
  directory = "netlify/functions"   # <— same here (being explicit helps)
  node_bundler = "esbuild"

